tasks:
  - name: Jekyll
    init: |
      mkdir -m 777 _site
      mkdir -m 777 .jekyll-cache
    command: docker run --volume="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:4.2.0 jekyll serve
    
ports:
  - port: 4000
    onOpen: open-preview
