baseURL: https://fmi-standard.org
title: Functional Mock-up Interface
theme: ma-hugo-theme
params:
  logo: /assets/images/FMI_bare.svg
  github: modelica/fmi-standard
  twitter: fmistandard
  uacode: UA-145375737-1  
menu:
  main:
    - pageRef: "tools"
      identifier: "tools"
      name: "Tools"
      url: "/tools/"
      weight: 1

    - pageRef: "literature"
      identifier: "literature"
      name: "Literature"
      url: "/literature/"
      weight: 2

    - pageRef: "news"
      identifier: "news"
      name: "News"
      url: "/news/"
      weight: 3

    - pageRef: "about"
      identifier: "about"
      name: "About"
      url: "/about/"
      weight: 4

    - pageRef: "faq"
      identifier: "faq"
      name: "FAQ"
      url: "/faq/"
      weight: 5
