baseURL: "https://fmi-standard.org"
title: "Functional Mock-up Interface"

menu:
  main:
    - pageRef: "tools"
      identifier: "tools"
      name: "Tools"
      url: "/tools/"
      weight: 1

    - pageRef: "literature"
      identifier: "literature"
      name: "Literature"
      url: "/literature/"
      weight: 2

    - pageRef: "about"
      identifier: "about"
      name: "About"
      url: "/about/"
      weight: 3
    
    - pageRef: "faq"
      identifier: "faq"
      name: "FAQ"
      url: "/faq/"
      weight: 4
